services:
  mysql:
    image: mysql:8.4
    container_name: backend-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: flashcard_db
      MYSQL_USER: flashcard
      MYSQL_PASSWORD: flashcard123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
